# Generated by Django 6.0.6 on 2026-06-12 19:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('hysteria', 'Hysteria2'), ('vless', 'VLESS')], max_length=10)),
                ('vpn_email', models.EmailField(max_length=254, unique=True)),
                ('vpn_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('vpn_inbound_id', models.IntegerField()),
                ('vpn_sub_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_expiry', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'protocol')},
            },
        ),
    ]
