# Generated by Django 6.0.6 on 2026-06-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminsettings_profile_total_gb'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vpn_client_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
