# Generated by Django 6.0.6 on 2026-06-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_activation_code_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='source',
            field=models.CharField(default='donationalerts', max_length=20),
        ),
    ]
