# Generated by Django 6.0.6 on 2026-06-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_donation_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='footer_text',
            field=models.CharField(default='BETA-build v0.2 by V.', max_length=200, verbose_name='Текст в футере'),
        ),
    ]
