# Generated by Django 6.0.6 on 2026-06-16 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notification'),
        ('accounts', '0008_alter_profile_unique_together'),
    ]

    operations = [
    ]
