# Generated by Django 6.0.6 on 2026-06-17 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20260616_1237'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='payment_link',
            field=models.URLField(blank=True, verbose_name='Ссылка для оплаты'),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='payment_qr',
            field=models.TextField(blank=True, verbose_name='QR‑код оплаты (ссылка на изображение)'),
        ),
        migrations.CreateModel(
            name='PaymentTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_code', models.CharField(max_length=50)),
                ('screenshot', models.ImageField(upload_to='payment_screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
