# Generated by Django 6.0.6 on 2026-06-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='payment_qr',
            field=models.ImageField(blank=True, upload_to='payment_qr/', verbose_name='QR‑код оплаты'),
        ),
    ]
