# Generated by Django 6.0.6 on 2026-06-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentticket',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='paymentticket',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentticket',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
    ]
