# Generated by Django 6.0.6 on 2026-06-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='bank_details',
            field=models.TextField(blank=True, verbose_name='Реквизиты для перевода'),
        ),
    ]
